# Copyright © 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: photon
    image: photon:latest
    privileged: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: sleep 100m

  - name: centos-7
    image: centos:7
    command: /usr/lib/systemd/systemd

  - name: fedora-24
    image: fedora:24
    command: /lib/systemd/systemd

  - name: ubuntu-xenial
    image: ubuntu:16.04
    command: /lib/systemd/systemd

  - name: ubuntu-trusty
    image: ubuntu:14.04
    command: /sbin/init

  - name: ubuntu-precise
    image: ubuntu:12.04
    command: /sbin/init

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  enabled: false
  lint:
    name: flake8
